server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productcatalogdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: "Product-Catalog-Service"
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      dhanush:
        prod: DEBUG